Fix readme with correct badges and fix coverage.yml to ensure that test only passes if coverage is above 90%

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -47,14 +47,13 @@ jobs:
       - name: Run tests and generate coverage html
         run: (cd tests && ./run_tests.sh CI --cov=group9_package --cov-report=html:htmlcov)
 
-      # # Remove .gitignore file in test coverage data to be pushed to gh-pages
-      # # branch
-      # - name: Clean .gitignore in coverage output
-      #   run: rm -f tests/htmlcov/.gitignore
-
-      # # Deploy to gh-pages branch
-      # - name: Deploy test coverage GitHub page
-      #   uses: JamesIves/github-pages-deploy-action@3.6.2
-      #   with:
-      #     branch: gh-pages  # Replace 'gh-pages' with your target branch name
-      #     folder: tests/htmlcov
+      # Fail if coverage is less than 90%
+      - name: Check test coverage
+        run: |
+          coverage_percentage=$(grep -oP 'TOTAL\s+\K(\d+)%' tests/htmlcov/index.html | tr -d '%')
+          if [ "$coverage_percentage" -lt 90 ]; then
+            echo "Code coverage is below 90% ($coverage_percentage%)"
+            exit 1  # Fail the build
+          else
+            echo "Code coverage is $coverage_percentage%, meets the required threshold."
+          fi
